name: Daily Bing Wallpaper Update

on:
  schedule:
    # Run at 00:30 UTC every day
    - cron: '30 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-wallpapers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run wallpaper archiver
        run: python main.py
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Bing wallpapers: $(date -u +'%Y-%m-%d')" && git push)